server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  client_max_body_size 50m;

  location = /healthz {
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location ^~ /images/ {
    alias /images/;
    access_log off;
    expires 7d;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  gzip on;
  gzip_min_length 1024;
  gzip_types
    text/plain
    text/css
    application/javascript
    application/json
    application/xml
    image/svg+xml
    font/ttf
    font/otf
    application/font-woff
    application/font-woff2;

  location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf|eot)$ {
    access_log off;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location = /index.html {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
  }

  location = /api {
    return 301 /api/;
  }

  location = /api/healthz {
    proxy_pass http://tratorbr-plataforma-api:3069/healthz;
    proxy_http_version 1.1;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/ {
    proxy_pass http://tratorbr-plataforma-api:3069;
    proxy_http_version 1.1;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Upgrade           $http_upgrade;
    proxy_set_header Connection        "upgrade";

    proxy_read_timeout 300s;
    proxy_send_timeout 300s;

    proxy_redirect off;

    add_header Cache-Control "no-cache, no-store, must-revalidate";
  }

  location / {
    try_files $uri /index.html;
  }
}
